<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-NLD5HU1" name="RetryMulitpleFailedTestCases" tests="12" failures="3" timestamp="10 Aug 2019 10:38:33 GMT" time="0.212" errors="0">
  <testcase name="test1" time="0.052" classname="com.testcases.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="com.testcases.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="com.testcases.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="com.testcases.RetryLogicTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.testcases.RetryLogicTest.test1(RetryLogicTest.java:10)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.004" classname="com.testcases.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="com.testcases.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.004" classname="com.testcases.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.004" classname="com.testcases.RetryLogicTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.testcases.RetryLogicTest.test2(RetryLogicTest.java:15)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.004" classname="com.testcases.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="com.testcases.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="com.testcases.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="com.testcases.RetryLogicTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.testcases.RetryLogicTest.test3(RetryLogicTest.java:20)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- RetryMulitpleFailedTestCases -->
